### ISSUE TITLE
Interface needs type assertion

### ISSUE THREAD

**Issue by TheHackerDev** [CaliDog/certstream-go#1]
I get the following error at https://github.com/CaliDog/certstream-go/blob/master/certstream.go#L33:

`cannot use v (type interface {}) as type string in argument to log.Info: need type assertion`

It looks like you'll have to define the interface a little more, or add a String() method to be able to output to `log.Info()`.

Cheers,
Aaron ([insp3ctre](https://twitter.com/insp3ctre))

**Comment by Fitblip** [comment]
Hey @insp3ctre,

I think that I should actually just remove this. I believe I had it in for debug reasons, but it doesn't do anyone any good to just barf raw json into the logger anyway!

Thanks for the heads up, I'll fix it shortly :D

**Comment by Fitblip** [comment]
This should be fixed with https://github.com/CaliDog/certstream-go/commit/fa8151c06b3a4db38fe431a9cfa57d951f13df41

Let me know if you have any other issues or anything else you'd change about the lib! Thanks again for the reports :)

Have a great rest of your week!

**Comment by TheHackerDev** [comment]
That works, I agree. Thanks @Fitblip. 

Cheers,
Aaron ([insp3ctre](https://twitter.com/insp3ctre))
